#!/usr/bin/bash

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any command fails
set -o errexit

echo "* ensure latest packages"
uptodate

echo "* Activate zabbix check"
ln -nfs /opt/local/lib/zabbix/ps_ /opt/local/lib/zabbix/ps_delayed_job

echo "* Setup ruby env"
echo "gem: --no-document " >> /opt/local/etc/gemrc
gem update --system
gem install bundler
gem install gemenv
gem install pkg-config

echo "* Setup ruby home"
groupadd -g 1100 ruby
useradd -m -s /usr/bin/bash -d /home/ruby -u 1100 -g ruby ruby
passwd -N ruby
passwd -d ruby

cat >> /home/ruby/.bashrc << EOF
source /home/ruby/www/shared/gems/bin/activate
TMPDIR="/var/tmp"
EOF
cat >> /home/ruby/.bash_history << EOF
#`date +'%s'`
cd /home/ruby/www/current
EOF

mkdir -p /home/ruby/www/releases
mkdir -p /home/ruby/www/shared/config
mkdir -p /home/ruby/www/shared/content
mkdir -p /home/ruby/www/shared/log
mkdir -p /home/ruby/www/shared/system
cd /home/ruby/www/shared
/opt/local/bin/gemenv gems

mv /opt/local/var/tmp/activate /home/ruby/www/shared/gems/bin/activate
mv /opt/local/var/tmp/ruby /home/ruby/www/shared/gems/bin/ruby
chmod +x /home/ruby/www/shared/gems/bin/ruby
chown -R ruby:ruby /home/ruby

# Configuring image specific packages
echo "* Configuring image specific packages.";
mkdir -p /var/log/httpd/old
mkdir -p /opt/local/etc/httpd/ssl || true
chmod 0640 /opt/local/etc/httpd/ssl
ln -nfs /opt/local/etc/httpd/ssl /opt/local/etc/httpd/tls

echo "* Fix passenger";
echo "export PASSENGER_INSTANCE_REGISTRY_DIR=/var/tmp" >> /root/.bashrc
# fix wrong passenger pkgsrc build 2017Q4 for ruby 2.7
# ln -nfs /opt/local/lib/ruby/vendor_ruby/2.7.0 /opt/local/lib/ruby/vendor_ruby/2.2.0

echo "* Import ruby process watcher";
svccfg import /opt/qutic/lib/svc/manifest/rbpswatch.xml
# svcadm enable rbpswatch

echo "* Add squoosh image compression app with cli";
npm i -g squoosh
npm i -g @squoosh/cli

echo "* Add commands to bash-history";
cat >> /root/.bash_history << EOF
/lib/svc/bin/svc.configd 
EOF

# Clean up
echo "* Cleaning up."
#pkgin -y remove gmake
#pkgin -y remove gcc10
rm /root/customize
rm -rf /opt/local/var/tmp

# Prepare image for provisioning
sm-prepare-image -y
